### ISSUE TITLE
Rss feed of new albums

### ISSUE THREAD

**Issue by eelcoj** [DroptuneHQ/droptune#28]
Add a Rss feed to get new albums (still follow blogs for this reason!). (Happy to spend some time on it soon.)

**Comment by Shpigford** [comment]
RSS to pull in new albums _in_ to Droptune? Or RSS to pull new albums _out_ of Droptune?

**Comment by eelcojellema** [comment]
Haha. Wups! Wanting a Droptune RSS feed that lets you get new albums in your feed reader.

**Comment by Shpigford** [comment]
This has been implemented!
