### ISSUE TITLE
Duplicates in latest and upcoming releases

### ISSUE THREAD

**Issue by orangemooncreative** [DroptuneHQ/droptune#63]
I have a bunch of duplicates from apple music in both of these sections. Not sure why. I checked to see if it was because of different types (explicit and clean versions) but that's not it. I have singles and compilations off.

Here is an example from the upcoming release section:

![duplicates-1](https://user-images.githubusercontent.com/1316656/45005981-2b376b00-b029-11e8-965e-3e5a2abe656a.jpg)

**Comment by orangemooncreative** [comment]
Actually....after posting I see the issue. I see for some there is a slight variation in the artist names for the duplicates (i.e. ghostface vs ghostface killah | Too Short vs Too $Short). But with some the names are the same and still duplicating (i.e. guilty simpson and too short).

**Comment by Shpigford** [comment]
Thanks for reporting this. It's a really tricky issue to properly merge artists (since they can exist in lots of different forms).

Will work on these.

**Comment by Shpigford** [comment]
This should be fixed now!
