### ISSUE TITLE
500 Error for Apple Music Sync

### ISSUE THREAD

**Issue by flybayer** [DroptuneHQ/droptune#68]
I had previously signed up as `flybayer` and connected Apple Music and Spotify. I was getting a bunch of new music I didn't care about from my Spotify graveyard. So to remove all those I canceled my Droptune account, and then created a new one with the same Twitter.

Right after first login to the new account, the Apple Music button says "Refresh Apple Music Library" instead of "Connect".

When I click "Refresh Apple Music Library" the button text changes to "Scanning .." but the API call returns a 500 error.

Looks like I hit an unexpected edge case 😬

**Comment by Shpigford** [comment]
This should be fixed!
