### ISSUE TITLE
Support for Bandcamp and Discogs

### ISSUE THREAD

**Issue by maartenafink** [DroptuneHQ/droptune#92]
It would be awesome to add support for both Bandcamp and Discogs. Mainly the reason to also follow your underrepresented artists, who are often only available on Bandcamp. The reason for Discogs is to follow artists who only release on vinyl, their releases are not available on digital streaming platforms.

They both have an available API:

Bandcamp
https://bandcamp.com/developer

Discogs
https://www.discogs.com/developers

**Comment by Shpigford** [comment]
Great idea!

**Comment by Shpigford** [comment]
Did some digging here and, unfortunately, the Bandcamp API is only for labels/bands/merch partners. The API doesn't give access to individual accounts, so there's no way to pull things like follows/purchases, or even data on individual bands.

Discogs is a _maybe_...they've certainly got a lot of data, which is sort of the problem. Will likely be difficult to merge it with existing data

I'm actually going to close this issue and if you feel strongly that Discogs has a lot of releases not available on Spotify/Apple, feel free to create a new issue for just that.
